### ISSUE TITLE
Get as much info as possible from the schemas

### ISSUE THREAD

**Issue by HendrikThePendric** [dhis2/mar-y#24]
Looking at the `./src/constants/sections.js` file, and assuming we’ll be using schemas from the api, I think we could strip the permissions arrays from the section objects, because this info is available on the metadata schema. And it is possible that authority names change.

i.e. https://play.dhis2.org/dev/api/schemas/category.json will provide us with the same info as we have hardcoded in that file.

And, as you can see at the url above, the schemas contain a wealth of other information which can be leveraged for forms etc.

**Comment by Mohammer5** [comment]
Keeping this one open

**Comment by Mohammer5** [comment]
Done
