### ISSUE TITLE
Create unambiguous and clear naming of app entities

### ISSUE THREAD

**Issue by HendrikThePendric** [dhis2/mar-y#25]
There are multiple "layers" in this app. Currently these are structured like this:
1. **Sections**: i.e. Category, which is a group that holds all category related metadata object types, such as Category option, Category, Category combination, etc.
2. **Sub-sections**: the metadata object types which are grouped under a section
3. **Currently unnamed**: the different views for each metadata object type

I propose we define them as follows:
1) ~Sections~ Groups
2) ~Sub-sections~ Sections
3) ~Currently unnamed~ SectionViews

To me this seems pretty descriptive and we won't get em mixed up.

It will not only benefit our code, but also our communication, if we create clear definitions upfront.

**Comment by Mohammer5** [comment]
Keeping this one open

**Comment by Mohammer5** [comment]
I've renamed sections and sub sections to groups and sections.
For SectionViews, right now they're called pages. Please have a look at what I've proposed in #47 with the pages (controller like code)

**Comment by HendrikThePendric** [comment]
This has been addressed
